import subprocess
import time
from pathlib import Path
import sys
from datetime import datetime
import os

class FixedOrchestrator:
    def __init__(self, vault_path):
        self.vault_path = Path(vault_path)
        self.scripts_path = self.vault_path / 'Scripts'
        self.logs_path = self.vault_path / 'Logs'
        self.needs_action = self.vault_path / 'Needs_Action'
        self.plans = self.vault_path / 'Plans'
        
        # Create directories
        self.plans.mkdir(exist_ok=True)
        (self.vault_path / 'Done').mkdir(exist_ok=True)
        (self.vault_path / 'Done' / datetime.now().strftime("%Y-%m-%d")).mkdir(exist_ok=True, parents=True)
        
    def log(self, message):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_entry = f"[{timestamp}] {message}\n"
        print(log_entry.strip())
        
        log_file = self.logs_path / f'worker_{datetime.now().strftime("%Y%m%d")}.log'
        with open(log_file, 'a', encoding='utf-8') as f:
            f.write(log_entry)
    
    def run_gmail_watcher(self):
        """Run Gmail watcher script"""
        self.log("📧 Running Gmail watcher...")
        try:
            result = subprocess.run(
                [sys.executable, 'gmail_watcher.py'],
                cwd=str(self.scripts_path),
                capture_output=True,
                text=True,
                timeout=120
            )
            if result.returncode == 0:
                self.log("✅ Gmail watcher completed")
                files = list(self.needs_action.glob('EMAIL_*.md'))
                self.log(f"📊 Email files in Needs_Action: {len(files)}")
                return True
            else:
                self.log(f"❌ Error: {result.stderr}")
                return False
        except Exception as e:
            self.log(f"❌ Exception: {str(e)}")
            return False
    
    def create_plan_with_kiro(self, email_file):
        """Create plan using Kiro (fixed stdin method)"""
        filename = email_file.name
        plan_name = filename.replace('.md', '_plan.md')
        plan_path = self.plans / plan_name
        
        # Read email content
        try:
            email_content = email_file.read_text(encoding='utf-8')
            
            # Extract key info for prompt
            lines = email_content.split('\n')
            from_field = "Unknown"
            subject = "No Subject"
            preview = ""
            
            for line in lines:
                if line.startswith('from:'):
                    from_field = line.replace('from:', '').strip()
                elif line.startswith('subject:'):
                    subject = line.replace('subject:', '').strip()
                elif '### Preview' in line:
                    idx = lines.index(line)
                    if idx + 1 < len(lines):
                        preview = lines[idx + 1].strip()
            
            # Create prompt - Kiro needs input via stdin
            prompt = f"""Create a simple action plan for this email:

From: {from_field}
Subject: {subject}
Preview: {preview[:200]}

Create a plan with:
1. SUMMARY (one line)
2. ACTION ITEMS (checklist)
3. PRIORITY (High/Medium/Low)

Keep it short and simple."""
            
        except Exception as e:
            self.log(f"❌ Error reading file: {e}")
            return self.create_fallback_plan(email_file, plan_path)
        
        try:
            # Run Kiro with stdin input (CORRECT METHOD)
            process = subprocess.Popen(
                ['C:\\Users\\afroz\\AppData\\Local\\Programs\\Kiro\\bin\\kiro.cmd'],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                cwd=str(self.vault_path)
            )
            
            stdout, stderr = process.communicate(input=prompt, timeout=30)
            
            if process.returncode == 0 and stdout.strip():
                final_plan = f"""---
created: {datetime.now().isoformat()}
source: {filename}
generator: Kiro
status: pending
---

{stdout}

---
*Generated by AI Employee*
"""
                plan_path.write_text(final_plan, encoding='utf-8')
                self.log(f"✅ Created plan with Kiro: {plan_name}")
                return True
            else:
                self.log(f"❌ Kiro failed for {filename}")
                if stderr:
                    self.log(f"Stderr: {stderr}")
                return self.create_fallback_plan(email_file, plan_path)
                
        except Exception as e:
            self.log(f"❌ Error with Kiro: {e}")
            return self.create_fallback_plan(email_file, plan_path)
    
    def create_plan_with_claude(self, email_file):
        """Create plan using Claude Code (fixed method)"""
        filename = email_file.name
        plan_name = filename.replace('.md', '_plan.md')
        plan_path = self.plans / plan_name
        
        # Read email content
        try:
            email_content = email_file.read_text(encoding='utf-8')
            
            # Create prompt file for Claude
            prompt = f"""Create a plan for this email:

{email_content[:500]}

Create a plan with:
1. Summary
2. Action items
3. Priority
4. Notes

Keep it concise."""
            
        except Exception as e:
            self.log(f"❌ Error reading file: {e}")
            return self.create_fallback_plan(email_file, plan_path)
        
        try:
            # Save prompt to temp file
            temp_file = self.vault_path / 'temp_prompt.txt'
            temp_file.write_text(prompt, encoding='utf-8')
            
            # Run Claude with the file (using @ symbol instead of -f)
            result = subprocess.run(
                ['claude', '@' + str(temp_file)],
                cwd=str(self.vault_path),
                capture_output=True,
                text=True,
                timeout=60
            )
            
            # Clean up temp file
            if temp_file.exists():
                temp_file.unlink()
            
            if result.returncode == 0 and result.stdout.strip():
                final_plan = f"""---
created: {datetime.now().isoformat()}
source: {filename}
generator: Claude
status: pending
---

{result.stdout}

---
*Generated by AI Employee*
"""
                plan_path.write_text(final_plan, encoding='utf-8')
                self.log(f"✅ Created plan with Claude: {plan_name}")
                return True
            else:
                self.log(f"❌ Claude failed for {filename}")
                return self.create_fallback_plan(email_file, plan_path)
                
        except Exception as e:
            self.log(f"❌ Error with Claude: {e}")
            return self.create_fallback_plan(email_file, plan_path)
    
    def create_fallback_plan(self, email_file, plan_path):
        """Create a simple fallback plan"""
        filename = email_file.name
        
        # Extract basic info
        try:
            content = email_file.read_text(encoding='utf-8')
            from_field = "Unknown"
            subject = "No Subject"
            
            lines = content.split('\n')
            for line in lines:
                if line.startswith('from:'):
                    from_field = line.replace('from:', '').strip()
                elif line.startswith('subject:'):
                    subject = line.replace('subject:', '').strip()
        except:
            from_field = "Unknown"
            subject = "No Subject"
        
        plan_content = f"""---
created: {datetime.now().isoformat()}
source: {filename}
generator: Fallback
status: pending
---

# EMAIL PLAN: {filename}

## 📧 Summary
Email from: {from_field}
Subject: {subject}

## ✅ Manual Actions Required
- [ ] Read the email
- [ ] Determine action needed
- [ ] Reply if required
- [ ] Move to Done when complete

## 🚨 Priority
Medium

---
*Auto-generated (Fallback Mode)*
"""
        plan_path.write_text(plan_content, encoding='utf-8')
        self.log(f"⚠️ Created fallback plan: {filename}")
        return True
    
    def process_emails(self):
        """Process all emails"""
        email_files = list(self.needs_action.glob('EMAIL_*.md'))
        
        if not email_files:
            self.log("📭 No emails to process")
            return []
        
        self.log(f"📧 Processing {len(email_files)} emails...")
        
        # Try Kiro first (since it's working based on your test)
        successful = []
        failed = []
        
        for i, email_file in enumerate(email_files, 1):
            self.log(f"\n[{i}/{len(email_files)}] Processing: {email_file.name}")
            
            # Try Kiro
            if self.create_plan_with_kiro(email_file):
                successful.append(email_file)
            else:
                # If Kiro fails, try Claude
                self.log("🔄 Trying Claude as backup...")
                if self.create_plan_with_claude(email_file):
                    successful.append(email_file)
                else:
                    failed.append(email_file)
            
            time.sleep(2)  # Small delay
        
        self.log(f"\n✅ Successful: {len(successful)}")
        self.log(f"❌ Failed: {len(failed)}")
        
        return successful
    
    def move_to_done(self):
        """Move processed emails to Done folder"""
        plan_files = list(self.plans.glob('*_plan.md'))
        
        if not plan_files:
            self.log("📭 No plans to move")
            return
        
        today = datetime.now().strftime("%Y-%m-%d")
        done_today = self.vault_path / 'Done' / today
        done_today.mkdir(exist_ok=True)
        
        moved = 0
        for plan in plan_files:
            original_name = plan.name.replace('_plan.md', '.md')
            original_path = self.needs_action / original_name
            
            if original_path.exists():
                # Move both files
                original_path.rename(done_today / original_name)
                plan.rename(done_today / plan.name)
                self.log(f"✅ Moved: {original_name} -> Done/{today}/")
                moved += 1
        
        self.log(f"📊 Total moved: {moved}")
    
    def update_dashboard(self):
        """Update dashboard"""
        dashboard = self.vault_path / 'Dashboard.md'
        
        pending = len(list(self.needs_action.glob('*.md')))
        plans = len(list(self.plans.glob('*_plan.md')))
        
        content = f"""# 🤖 AI EMPLOYEE DASHBOARD

## 📊 Status
**Last Updated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Status:** 🟢 Active

## 📥 Queue
- **Pending:** {pending}
- **Plans:** {plans}

## ✅ Recent
"""
        dashboard.write_text(content, encoding='utf-8')
        self.log("📊 Dashboard updated")
    
    def run_once(self):
        """Run one cycle"""
        self.log("\n" + "="*60)
        self.log("🚀 AI EMPLOYEE - STARTING")
        self.log("="*60)
        
        # Step 1: Get emails
        if self.run_gmail_watcher():
            # Step 2: Process them
            processed = self.process_emails()
            
            # Step 3: Show results
            if processed:
                print(f"\n✅ Processed {len(processed)} emails")
                self.move_to_done()
        
        # Step 4: Update dashboard
        self.update_dashboard()
        
        self.log("="*60)
        self.log("✅ CYCLE COMPLETE")
        self.log("="*60)

def main():
    vault_path = r"C:\Users\afroz\OneDrive\Desktop\AI_Employee_Vault"
    orch = FixedOrchestrator(vault_path)
    
    print("╔════════════════════════════╗")
    print("║   AI EMPLOYEE - WORKER     ║")
    print("╚════════════════════════════╝\n")
    
    orch.run_once()

if __name__ == "__main__":
    main()